users:
  name:
    max_length: 55
  email:
    max_length: 255
  password:
    min_length: 8
  phone_number:
    max_length: 11
  address:
    min_length: 50
    max_length: 255
comments:
  content:
    min_length: 80
products:
  name:
    min_length: 20
per:
  limit_page: 10
  limit_filter: 9
  product:
    limit_page: 12
order_details:
  quantity:
    default: 1
product:
  name:
    min_length: 6
  describe:
    min_length: 6
  picture:
    max_size: 5
    size: 200
uploader:
  picture: 300
inputs:
  default_floor: 0
  default_ceil: 1000000
  step_filter: 500000
  max_ram: 32
  medium_ram: 16
  low_ram: 8
  min_ram: 4
picture:
  max_size: 10
update_picture:
  max_size: 80
